# ===============================
# SERVER CONFIG
# ===============================
server.port=8090
spring.application.name=quiz-service

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/student_analytics_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# CONNECTION POOL (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
nlp.service.url=http://localhost:5001
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.example.quiz_service=DEBUG

# ===============================
# EXTERNAL SERVICE URLs
# ===============================
ai.service.url=http://localhost:5001
performance.service.url=http://localhost:8083