# ==========================================
# 13. AI-INTEGRATION-SERVICE (Port 8087)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: ai-integration-service
spec:
  ports:
    - port: 8087
  selector:
    app: ai-integration-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-integration-service
spec:
  selector:
    matchLabels:
      app: ai-integration-service
  template:
    metadata:
      labels:
        app: ai-integration-service
    spec:
      containers:
      - name: ai-integration-service
        image: rsujal/edupulse-ai-integration-service:v1
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: edupulse-config
        resources:
          limits:
            memory: "512Mi"

---
# ==========================================
# 14. ANALYTICS-SERVICE (Port 8086)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  ports:
    - port: 8086
  selector:
    app: analytics-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: rsujal/edupulse-analytics-service:v1
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: edupulse-config
        resources:
          limits:
            memory: "512Mi"

---
# ==========================================
# 15. EXAM-RESULT-SERVICE (Port 8088)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: exam-result-service
spec:
  ports:
    - port: 8088
  selector:
    app: exam-result-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-result-service
spec:
  selector:
    matchLabels:
      app: exam-result-service
  template:
    metadata:
      labels:
        app: exam-result-service
    spec:
      containers:
      - name: exam-result-service
        image: rsujal/edupulse-exam-result-service:v1
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: edupulse-config
        resources:
          limits:
            memory: "512Mi"
