apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: basicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: sujal/question-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: basicapp
spec:
  selector:
    app: question-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
