apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: basicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: sujal/quiz-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: basicapp
spec:
  selector:
    app: quiz-service
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
