apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: basicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sujal/user-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: MYSQL_HOST
              value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: basicapp
spec:
  selector:
    app: user-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
