apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: basicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: rsujal/service-registry:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: basicapp
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP