apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: basicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: rsujal/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

          # --- MOUNT THE STORAGE ---
          volumeMounts:
            - name: reports-storage
              mountPath: /app/files
          
      # --- DEFINE THE STORAGE ---
      volumes:
        - name: reports-storage
          persistentVolumeClaim:
            claimName: quiz-reports-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: basicapp
spec:
  selector:
    app: user-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP 