# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4i3VvmW2utZswzaZJWRlkX2_LaTMDlv
"""

from ollama import Client

client = Client(
    host="http://localhost:11434/"
)

response = client.chat(
    model="gemma2:2b",
    messages=[
        {
            "role": "system",
            "content":"You are a helpful chat assistant"
        },
        {
            "role":"user",
            "content":"What is Artifical Intelligence? Explain in short"
        }
    ],
    stream=True
)


for chunk in response:
  print(chunk["message"]["content"],end="",flush=True)
