#spring.application.name=product-microservice



#
##server.port=8080
#
##spring.kafka.producer.bootstrap-servers=[::1]:9092,[::1]:9094
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.admin.properties.request.timeout.ms=5000
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.add.type.headers=true
##spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
### Consumer Settings
##spring.kafka.consumer.group-id=verification-group
##spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
## FIX: Use ErrorHandlingDeserializer + JsonDeserializer for the value
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#
#spring.kafka.consumer.group-id=final-test-group-001
#spring.kafka.consumer.auto-offset-reset=earliest
## Trusted Packages (Crucial for JSON)
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.product_microservice.rest.ProductCreatedEvent

spring.application.name=product-microservice
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
#spring.kafka.consumer.group-id=group-final-verification-99
spring.kafka.consumer.group-id=force-read-group-101
#spring.kafka.consumer.auto-offset-reset=earlies
#spring.kafka.consumer.properties.spring.json.use.type.headers=fals
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.product_microservice.rest.ProductCreatedEvent
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Type Mapping overrides
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.product_microservice.rest.ProductCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*